# K-HTML Hackathon - 주제 3: 동대문 워킹도시

## Import 모듈

In [1]:
# Python 모듈
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

데이터 정제 및 가공

In [2]:
FOLDER_LOCATION = '/content/drive/MyDrive/BDA_k_html'
SEOUL_DONGDAEMUNGO_PARKINFORMATION_20240617 = pd.read_csv(f'{FOLDER_LOCATION}/SEOUL_DONGDAEMUNGO_PARKINFORMATION_20240617.csv', encoding='cp949')
SEOUL_DONGDAEMUNGO_PARKTREEINFORMATION_20221212 = pd.read_csv(f'{FOLDER_LOCATION}/SEOUL_DONGDAEMUNGO_PARKTREEINFORMATION_20221212.csv', encoding='cp949')
SEOUL_DONGDAEMUNGO_CROSSINFORMATION_20221212 = pd.read_csv(f'{FOLDER_LOCATION}/SEOUL_DONGDAEMUNGO_CROSSINFORMATION_20221212.csv', encoding='cp949')

In [3]:
SEOUL_DONGDAEMUNGO_PARKTREEINFORMATION_20221212.columns

Index(['관리번호', '수목명', '수목구분', '수목유형', '식재일', '관리기관전화번호', '관리기관명', '데이터기준일자',
       '공원명', '공원관리번호', '도로명주소', '지번주소', '수목위치', '수목위도', '수목경도', '흉고직경',
       '근원직경', '수령', '보호덮개', '보호틀', '뿌리융기여부', '통기', '지장물', '수목사진', '기타사진'],
      dtype='object')

In [4]:
SEOUL_DONGDAEMUNGO_PARKINFORMATION_20240617.columns

Index(['관리번호', '공원명', '공원구분', '소재지지번주소', '위도', '경도', '공원면적', '공원보유시설(교양시설)',
       '지정고시일', '관리기관명', '전화번호', '데이터기준일자'],
      dtype='object')

In [5]:
SEOUL_DONGDAEMUNGO_CROSSINFORMATION_20221212.columns

Index(['관리번호', '수목명', '수목구분', '수목유형', '식재일', '관리기관전화번호', '관리기관명', '데이터기준일자',
       '도로명', '도로종류', '도로시작점', '도로종료점', '수목위치', '수목위도', '수목경도', '도로명주소',
       '지번주소', '행정동', '흉고직경', '근원직경', '식재간격', '수령', '도로폭', '보도폭', '보호덮개',
       '보호틀', '보호틀파손여부', '뿌리융기여부', '통기', '지장물1', '지장물2', '수목전경사진', '보호덮개사진'],
      dtype='object')

In [6]:
SEOUL_DONGDAEMUNGO_PARKTREEINFORMATION_20221212 = SEOUL_DONGDAEMUNGO_PARKTREEINFORMATION_20221212.drop(['관리번호', '수목구분', '수목유형', '식재일', '관리기관전화번호', '관리기관명', '데이터기준일자', '공원관리번호', '도로명주소', '수목위치', '수목위도', '수목경도', '흉고직경', '근원직경', '수령', '보호덮개', '보호틀', '뿌리융기여부', '통기', '지장물', '수목사진', '기타사진'], axis=1)
SEOUL_DONGDAEMUNGO_PARKINFORMATION_20240617 = SEOUL_DONGDAEMUNGO_PARKINFORMATION_20240617.drop(['관리번호', '위도', '경도', '공원보유시설(교양시설)', '지정고시일', '관리기관명', '전화번호', '데이터기준일자'], axis=1)
SEOUL_DONGDAEMUNGO_CROSSINFORMATION_20221212 = SEOUL_DONGDAEMUNGO_CROSSINFORMATION_20221212.drop(['관리번호', '수목명', '수목구분', '수목유형', '식재일', '관리기관전화번호', '관리기관명', '데이터기준일자', '도로종류', '수목위도', '수목경도', '도로명주소', '행정동', '흉고직경', '근원직경', '식재간격', '수령', '도로폭', '보도폭', '보호덮개', '보호틀', '보호틀파손여부', '뿌리융기여부', '통기', '지장물1', '지장물2', '수목전경사진', '보호덮개사진'], axis=1)

In [7]:
SEOUL_DONGDAEMUNGO_PARKTREEINFORMATION_20221212.head()

     수목명     공원명                지번주소
0   모과나무  장안근린공원  서울특별시 동대문구 장안동 300
1   매실나무  장안근린공원  서울특별시 동대문구 장안동 300
2  양버즘나무  장안근린공원  서울특별시 동대문구 장안동 300
3   단풍나무  장안근린공원  서울특별시 동대문구 장안동 300
4   단풍나무  장안근린공원  서울특별시 동대문구 장안동 300

In [8]:
SEOUL_DONGDAEMUNGO_PARKINFORMATION_20240617.head()

    공원명   공원구분                소재지지번주소      공원면적
0    청량   근린공원   서울특별시 동대문구 청량리동 산1-1  119871.0
1   우산각  어린이공원   서울특별시 동대문구 신설동 109-4    5294.2
2  느티나무  어린이공원  서울특별시 동대문구 용두동 138-61    1719.0
3    안골  어린이공원     서울특별시 동대문구 장안동 402    1652.3
4  마로니에  어린이공원     서울특별시 동대문구 장안동 325    1656.2

In [9]:
SEOUL_DONGDAEMUNGO_PARKINFORMATION_20240617['공원통합명'] = SEOUL_DONGDAEMUNGO_PARKINFORMATION_20240617['공원명'] + SEOUL_DONGDAEMUNGO_PARKINFORMATION_20240617['공원구분']
SEOUL_DONGDAEMUNGO_PARKINFORMATION_20240617 = SEOUL_DONGDAEMUNGO_PARKINFORMATION_20240617.drop(['공원명', '공원구분'], axis=1)

In [10]:
SEOUL_DONGDAEMUNGO_CROSSINFORMATION_20221212.head()

,도로명,도로시작점,도로종료점,수목위치,지번주소
0,천호대로,서울특별시 동대문구 신설동 117-21,서울특별시 동대문구 장안동 204-13,천호대로 47 앞,서울특별시 동대문구 용두동 237-10
1,외대역동로,서울특별시 동대문구 휘경동 55-3,서울특별시 동대문구 이문동 101-37,동양엔파트 앞,서울특별시 동대문구 휘경동 112-43
2,제기로17길,서울특별시 동대문구 청량리동 520-55,서울특별시 동대문구 청량리동 205-293,서일eng 앞,서울특별시 동대문구 청량리동 203-316
3,천호대로,서울특별시 동대문구 신설동 117-21,서울특별시 동대문구 장안동 204-13,신답역 앞 정류장 앞,서울특별시 동대문구 답십리동 524-1
4,답십리로,서울특별시 동대문구 전농동 621-1,서울특별시 동대문구 장안동 333-2,대한열쇠 앞,서울특별시 동대문구 전농동 485-11

In [11]:
SEOUL_DONGDAEMUNGO_PARKTREEINFORMATION_20221212.to_csv(f'{FOLDER_LOCATION}/UPDATE_DATASET/SEOUL_DONGDAEMUNGO_PARKTREEINFORMATION.csv', encoding='cp949')
SEOUL_DONGDAEMUNGO_PARKINFORMATION_20240617.to_csv(f'{FOLDER_LOCATION}/UPDATE_DATASET/SEOUL_DONGDAEMUNGO_PARKINFORMATION.csv', encoding='cp949')
SEOUL_DONGDAEMUNGO_CROSSINFORMATION_20221212.to_csv(f'{FOLDER_LOCATION}/UPDATE_DATASET/SEOUL_DONGDAEMUNGO_CROSSINFORMATION.csv', encoding='cp949')

In [12]:
df_1 = SEOUL_DONGDAEMUNGO_PARKINFORMATION_20240617.merge(SEOUL_DONGDAEMUNGO_PARKTREEINFORMATION_20221212, how='left', left_on='공원통합명', right_on='공원명')
df_1.head()

                 소재지지번주소      공원면적      공원통합명  수목명  공원명 지번주소
0   서울특별시 동대문구 청량리동 산1-1  119871.0     청량근린공원  NaN  NaN  NaN
1   서울특별시 동대문구 신설동 109-4    5294.2   우산각어린이공원  NaN  NaN  NaN
2  서울특별시 동대문구 용두동 138-61    1719.0  느티나무어린이공원  NaN  NaN  NaN
3     서울특별시 동대문구 장안동 402    1652.3    안골어린이공원  NaN  NaN  NaN
4     서울특별시 동대문구 장안동 325    1656.2  마로니에어린이공원  NaN  NaN  NaN

In [13]:
df_2 = SEOUL_DONGDAEMUNGO_CROSSINFORMATION_20221212.merge(SEOUL_DONGDAEMUNGO_PARKTREEINFORMATION_20221212, how='left', left_on='지번주소', right_on='지번주소')
df_2.head()

,도로명,도로시작점,도로종료점,수목위치,지번주소,수목명,공원명
0,천호대로,서울특별시 동대문구 신설동 117-21,서울특별시 동대문구 장안동 204-13,천호대로 47 앞,서울특별시 동대문구 용두동 237-10,NaN,NaN
1,외대역동로,서울특별시 동대문구 휘경동 55-3,서울특별시 동대문구 이문동 101-37,동양엔파트 앞,서울특별시 동대문구 휘경동 112-43,NaN,NaN
2,제기로17길,서울특별시 동대문구 청량리동 520-55,서울특별시 동대문구 청량리동 205-293,서일eng 앞,서울특별시 동대문구 청량리동 203-316,NaN,NaN
3,천호대로,서울특별시 동대문구 신설동 117-21,서울특별시 동대문구 장안동 204-13,신답역 앞 정류장 앞,서울특별시 동대문구 답십리동 524-1,NaN,NaN
4,답십리로,서울특별시 동대문구 전농동 621-1,서울특별시 동대문구 장안동 333-2,대한열쇠 앞,서울특별시 동대문구 전농동 485-11,NaN,NaN

In [14]:
df_1 = df_1.drop(['공원면적','지번주소', '공원통합명'], axis=1)
df_2 = df_2.drop(['도로명', '도로시작점', '도로종료점', '수목위치'], axis=1)
df = pd.concat([df_1, df_2])
df.head()
df.to_csv(f'{FOLDER_LOCATION}/UPDATE_DATASET/UPDATED_DB.csv', encoding='cp949')

In [16]:
df.head()

                 소재지지번주소  수목명  공원명 지번주소
0   서울특별시 동대문구 청량리동 산1-1  NaN  NaN  NaN
1   서울특별시 동대문구 신설동 109-4  NaN  NaN  NaN
2  서울특별시 동대문구 용두동 138-61  NaN  NaN  NaN
3     서울특별시 동대문구 장안동 402  NaN  NaN  NaN
4     서울특별시 동대문구 장안동 325  NaN  NaN  NaN

In [17]:
df['공원명'].unique()

array([nan, '장안근린공원', '장평근린공원', '텃골근린공원', '새샘근린공원', '용두공원'], dtype=object)

In [18]:
df[df['공원명'] == '장안근린공원']['수목명'].unique()

array(['모과나무', '매실나무', '양버즘나무', '단풍나무', '목련', '잣나무', '오동나무', '이팝나무',
       '계수나무', '버드나무', '산딸나무', '은행나무', '소나무', '피나무', '사과나무', '산수유', '뽕나무',
       '향나무', '감나무', '가죽나무', '느티나무', '벚나무', '물푸레나무', '모감주나무', '메타세쿼이아',
       '아까시나무', '산사나무', '가문비나무', '칠엽수', '측백나무', '백합나무', '팥배나무'],
      dtype=object)